#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

#define MOVE_NONE                0
#define MOVE_ABSORB              1
#define MOVE_ACID                2
#define MOVE_ACID_ARMOR          3
#define MOVE_AERIAL_ACE          4
#define MOVE_AEROBLAST           5
#define MOVE_AGILITY             6
#define MOVE_AIR_CUTTER          7
#define MOVE_AMNESIA             8
#define MOVE_ANCIENT_POWER       9
#define MOVE_ARM_THRUST          10
#define MOVE_AROMATHERAPY        11
#define MOVE_ASSIST              12
#define MOVE_ASTONISH            13
#define MOVE_ATTRACT             14
#define MOVE_AURA_SPHERE         15
#define MOVE_AURORA_BEAM         16
#define MOVE_BARRAGE             17
#define MOVE_BARRIER             18
#define MOVE_BATON_PASS          19
#define MOVE_BEAT_UP             20
#define MOVE_BELLY_DRUM          21
#define MOVE_BIDE                22
#define MOVE_BIND                23
#define MOVE_BITE                24
#define MOVE_BLAST_BURN          25
#define MOVE_BLAZE_KICK          26
#define MOVE_BLIZZARD            27
#define MOVE_BLOCK               28
#define MOVE_BODY_SLAM           29
#define MOVE_BONEMERANG          30
#define MOVE_BONE_CLUB           31
#define MOVE_BONE_RUSH           32
#define MOVE_BOUNCE              33
#define MOVE_BRICK_BREAK         34
#define MOVE_BUBBLE              35
#define MOVE_BUBBLE_BEAM         36
#define MOVE_BUG_BUZZ            37
#define MOVE_BULK_UP             38
#define MOVE_BULLET_SEED         39
#define MOVE_CALM_MIND           40
#define MOVE_CAMOUFLAGE          41
#define MOVE_CHARGE              42
#define MOVE_CHARGE_BEAM         43
#define MOVE_CHARM               44
#define MOVE_CLAMP               45
#define MOVE_COMET_PUNCH         46
#define MOVE_CONFUSE_RAY         47
#define MOVE_CONFUSION           48
#define MOVE_CONSTRICT           49
#define MOVE_CONVERSION          50
#define MOVE_CONVERSION_2        51
#define MOVE_COSMIC_POWER        52
#define MOVE_COTTON_SPORE        53
#define MOVE_COUNTER             54
#define MOVE_COVET               55
#define MOVE_CRABHAMMER          56
#define MOVE_CROSS_CHOP          57
#define MOVE_CRUNCH              58
#define MOVE_CRUSH_CLAW          59
#define MOVE_CURSE               60
#define MOVE_CUT                 61
#define MOVE_DARK_PULSE          62
#define MOVE_DEFENSE_CURL        63
#define MOVE_DESTINY_BOND        64
#define MOVE_DETECT              65
#define MOVE_DIG                 66
#define MOVE_DISABLE             67
#define MOVE_DISARMING_CRY       68
#define MOVE_DIVE                69
#define MOVE_DIZZY_PUNCH         70
#define MOVE_DOOM_DESIRE         71
#define MOVE_DOUBLE_EDGE         72
#define MOVE_DOUBLE_KICK         73
#define MOVE_DOUBLE_SLAP         74
#define MOVE_DOUBLE_TEAM         75
#define MOVE_DRAGON_BREATH       76
#define MOVE_DRAGON_CLAW         77
#define MOVE_DRAGON_DANCE        78
#define MOVE_DRAGON_RAGE         79
#define MOVE_DRAGON_TAIL         80
#define MOVE_DRAIN_KISS          81
#define MOVE_DREAM_EATER         82
#define MOVE_DRILL_PECK          83
#define MOVE_DRILL_RUN           84
#define MOVE_DYNAMIC_PUNCH       85
#define MOVE_EARTHQUAKE          86
#define MOVE_EARTH_AURA          87
#define MOVE_EGG_BOMB            88
#define MOVE_EMBER               89
#define MOVE_ENCORE              90
#define MOVE_ENDEAVOR            91
#define MOVE_ENDURE              92
#define MOVE_ERUPTION            93
#define MOVE_EXPLOSION           94
#define MOVE_EXTRASENSORY        95
#define MOVE_EXTREME_SPEED       96
#define MOVE_FACADE              97
#define MOVE_FAKE_OUT            98
#define MOVE_FAKE_TEARS          99
#define MOVE_FALSE_SWIPE         100
#define MOVE_FEATHER_DANCE       101
#define MOVE_FEINT_ATTACK        102
#define MOVE_FIRE_BLAST          103
#define MOVE_FIRE_FANG           104
#define MOVE_FIRE_PUNCH          105
#define MOVE_FIRE_SPIN           106
#define MOVE_FISSURE             107
#define MOVE_FLAIL               108
#define MOVE_FLAMETHROWER        109
#define MOVE_FLAME_CHARGE        110
#define MOVE_FLAME_WHEEL         111
#define MOVE_FLASH               112
#define MOVE_FLASH_CANNON        113
#define MOVE_FLATTER             114
#define MOVE_FLY                 115
#define MOVE_FOCUS_BLAST         116
#define MOVE_FOCUS_ENERGY        117
#define MOVE_FOCUS_PUNCH         118
#define MOVE_FOLLOW_ME           119
#define MOVE_FORCE_PALM          120
#define MOVE_FORESIGHT           121
#define MOVE_FRENZY_PLANT        122
#define MOVE_FRUSTRATION         123
#define MOVE_FURY_ATTACK         124
#define MOVE_FURY_CUTTER         125
#define MOVE_FURY_SWIPES         126
#define MOVE_FUTURE_SIGHT        127
#define MOVE_GIGA_DRAIN          128
#define MOVE_GLARE               129
#define MOVE_GRASS_WHISTLE       130
#define MOVE_GROWL               131
#define MOVE_GROWTH              132
#define MOVE_GRUDGE              133
#define MOVE_GUILLOTINE          134
#define MOVE_GUST                135
#define MOVE_HAIL                136
#define MOVE_HARDEN              137
#define MOVE_HAZE                138
#define MOVE_HEADBUTT            139
#define MOVE_HEAL_BELL           140
#define MOVE_HEAT_WAVE           141
#define MOVE_HELPING_HAND        142
#define MOVE_HIDDEN_POWER        143
#define MOVE_HI_JUMP_KICK        144
#define MOVE_HORN_ATTACK         145
#define MOVE_HORN_DRILL          146
#define MOVE_HOWL                147
#define MOVE_HYDRO_CANNON        148
#define MOVE_HYDRO_PUMP          149
#define MOVE_HYPER_BEAM          150
#define MOVE_HYPER_FANG          151
#define MOVE_HYPER_VOICE         152
#define MOVE_HYPNOSIS            153
#define MOVE_ICE_BALL            154
#define MOVE_ICE_BEAM            155
#define MOVE_ICE_FANG            156
#define MOVE_ICE_PUNCH           157
#define MOVE_ICICLE_SPEAR        158
#define MOVE_ICY_WIND            159
#define MOVE_IMPRISON            160
#define MOVE_INFESTATION         161
#define MOVE_INGRAIN             162
#define MOVE_IRON_DEFENSE        163
#define MOVE_IRON_HEAD           164
#define MOVE_IRON_TAIL           165
#define MOVE_JUMP_KICK           166
#define MOVE_KARATE_CHOP         167
#define MOVE_KINESIS             168
#define MOVE_KNOCK_OFF           169
#define MOVE_LAVA_PLUME          170
#define MOVE_LEAF_BLADE          171
#define MOVE_LEECH_LIFE          172
#define MOVE_LEECH_SEED          173
#define MOVE_LEER                174
#define MOVE_LICK                175
#define MOVE_LIGHT_SCREEN        176
#define MOVE_LOCK_ON             177
#define MOVE_LOW_KICK            178
#define MOVE_LULLABY_KISS        179
#define MOVE_LUSTER_PURGE        180
#define MOVE_MACH_PUNCH          181
#define MOVE_MAGICAL_LEAF        182
#define MOVE_MAGIC_COAT          183
#define MOVE_MAGNITUDE           184
#define MOVE_MEAN_LOOK           185
#define MOVE_MEDITATE            186
#define MOVE_MEGAHORN            187
#define MOVE_MEGA_DRAIN          188
#define MOVE_MEGA_KICK           189
#define MOVE_MEGA_PUNCH          190
#define MOVE_MEMENTO             191
#define MOVE_METAL_CLAW          192
#define MOVE_METAL_SOUND         193
#define MOVE_METEOR_MASH         194
#define MOVE_METRONOME           195
#define MOVE_MILK_DRINK          196
#define MOVE_MIMIC               197
#define MOVE_MIND_READER         198
#define MOVE_MINIMIZE            199
#define MOVE_MIRROR_COAT         200
#define MOVE_MIRROR_MOVE         201
#define MOVE_MIST                202
#define MOVE_MIST_BALL           203
#define MOVE_MOONBLAST           204
#define MOVE_MOONLIGHT           205
#define MOVE_MORNING_SUN         206
#define MOVE_MUDDY_WATER         207
#define MOVE_MUD_BOMB            208
#define MOVE_MUD_SHOT            209
#define MOVE_MUD_SLAP            210
#define MOVE_MUD_SPORT           211
#define MOVE_NATURE_POWER        212
#define MOVE_NEEDLE_ARM          213
#define MOVE_NIGHTMARE           214
#define MOVE_NIGHT_SHADE         215
#define MOVE_OCTAZOOKA           216
#define MOVE_ODOR_SLEUTH         217
#define MOVE_OUTRAGE             218
#define MOVE_OVERHEAT            219
#define MOVE_PAIN_SPLIT          220
#define MOVE_PAY_DAY             221
#define MOVE_PECK                222
#define MOVE_PERISH_SONG         223
#define MOVE_PETAL_DANCE         224
#define MOVE_PIN_MISSILE         225
#define MOVE_POISON_FANG         226
#define MOVE_POISON_GAS          227
#define MOVE_POISON_POWDER       228
#define MOVE_POISON_STING        229
#define MOVE_POISON_TAIL         230
#define MOVE_POUND               231
#define MOVE_POWDER_SNOW         232
#define MOVE_PRESENT             233
#define MOVE_PROTECT             234
#define MOVE_PSYBEAM             235
#define MOVE_PSYCHIC             236
#define MOVE_PSYCHO_BOOST        237
#define MOVE_PSYCH_UP            238
#define MOVE_PSYWAVE             239
#define MOVE_PURSUIT             240
#define MOVE_QUICK_ATTACK        241
#define MOVE_RAGE                242
#define MOVE_RAGE_POWDER         243
#define MOVE_RAIN_DANCE          244
#define MOVE_RAPID_SPIN          245
#define MOVE_RAZOR_LEAF          246
#define MOVE_RAZOR_WIND          247
#define MOVE_RECOVER             248
#define MOVE_RECYCLE             249
#define MOVE_REFLECT             250
#define MOVE_REFRESH             251
#define MOVE_REST                252
#define MOVE_RETURN              253
#define MOVE_REVENGE             254
#define MOVE_REVERSAL            255
#define MOVE_ROAR                256
#define MOVE_ROCK_BLAST          257
#define MOVE_ROCK_SLIDE          258
#define MOVE_ROCK_SMASH          259
#define MOVE_ROCK_THROW          260
#define MOVE_ROCK_TOMB           261
#define MOVE_ROLE_PLAY           262
#define MOVE_ROLLING_KICK        263
#define MOVE_ROLLOUT             264
#define MOVE_SACRED_FIRE         265
#define MOVE_SAFEGUARD           266
#define MOVE_SANDSTORM           267
#define MOVE_SAND_ATTACK         268
#define MOVE_SAND_TOMB           269
#define MOVE_SCARY_FACE          270
#define MOVE_SCRATCH             271
#define MOVE_SCREECH             272
#define MOVE_SECRET_POWER        273
#define MOVE_SEISMIC_TOSS        274
#define MOVE_SELF_DESTRUCT       275
#define MOVE_SHADOW_BALL         276
#define MOVE_SHADOW_PUNCH        277
#define MOVE_SHARPEN             278
#define MOVE_SHEER_COLD          279
#define MOVE_SHOCK_WAVE          280
#define MOVE_SIGNAL_BEAM         281
#define MOVE_SILVER_WIND         282
#define MOVE_SING                283
#define MOVE_SKETCH              284
#define MOVE_SKILL_SWAP          285
#define MOVE_SKULL_BASH          286
#define MOVE_SKY_ATTACK          287
#define MOVE_SKY_UPPERCUT        288
#define MOVE_SLACK_OFF           289
#define MOVE_SLAM                290
#define MOVE_SLASH               291
#define MOVE_SLEEP_POWDER        292
#define MOVE_SLEEP_TALK          293
#define MOVE_SLUDGE              294
#define MOVE_SLUDGE_BOMB         295
#define MOVE_SMELLING_SALT       296
#define MOVE_SMOG                297
#define MOVE_SMOKESCREEN         298
#define MOVE_SNARL               299
#define MOVE_SNATCH              300
#define MOVE_SNORE               301
#define MOVE_SOFT_BOILED         302
#define MOVE_SOLAR_BEAM          303
#define MOVE_SONIC_BOOM          304
#define MOVE_SPARK               305
#define MOVE_SPIDER_WEB          306
#define MOVE_SPIKES              307
#define MOVE_SPIKE_CANNON        308
#define MOVE_SPITE               309
#define MOVE_SPIT_UP             310
#define MOVE_SPLASH              311
#define MOVE_SPORE               312
#define MOVE_STEEL_WING          313
#define MOVE_STOCKPILE           314
#define MOVE_STOMP               315
#define MOVE_STONE_SURGE         316
#define MOVE_STRENGTH            317
#define MOVE_STRING_SHOT         318
#define MOVE_STRUGGLE            319
#define MOVE_STRUGGLE_BUG        320
#define MOVE_STUN_SPORE          321
#define MOVE_SUBMISSION          322
#define MOVE_SUBSTITUTE          323
#define MOVE_SUNNY_DAY           324
#define MOVE_SUPERPOWER          325
#define MOVE_SUPERSONIC          326
#define MOVE_SUPER_FANG          327
#define MOVE_SURF                328
#define MOVE_SWAGGER             329
#define MOVE_SWALLOW             330
#define MOVE_SWEET_KISS          331
#define MOVE_SWEET_SCENT         332
#define MOVE_SWIFT               333
#define MOVE_SWORDS_DANCE        334
#define MOVE_SYNTHESIS           335
#define MOVE_TACKLE              336
#define MOVE_TAIL_GLOW           337
#define MOVE_TAIL_WHIP           338
#define MOVE_TAKE_DOWN           339
#define MOVE_TAUNT               340
#define MOVE_TEETER_DANCE        341
#define MOVE_TELEPORT            342
#define MOVE_THIEF               343
#define MOVE_THRASH              344
#define MOVE_THUNDER             345
#define MOVE_THUNDERBOLT         346
#define MOVE_THUNDER_FANG        347
#define MOVE_THUNDER_PUNCH       348
#define MOVE_THUNDER_SHOCK       349
#define MOVE_THUNDER_WAVE        350
#define MOVE_TICKLE              351
#define MOVE_TORMENT             352
#define MOVE_TOXIC               353
#define MOVE_TRANSFORM           354
#define MOVE_TRICK               355
#define MOVE_TRIPLE_KICK         356
#define MOVE_TRI_ATTACK          357
#define MOVE_TWINEEDLE           358
#define MOVE_TWISTER             359
#define MOVE_UPROAR              360
#define MOVE_U_TURN              361
#define MOVE_VENOM_JAB           362
#define MOVE_VICE_GRIP           363
#define MOVE_VINE_WHIP           364
#define MOVE_VITAL_THROW         365
#define MOVE_VOLT_SWITCH         366
#define MOVE_VOLT_TACKLE         367
#define MOVE_WATERFALL           368
#define MOVE_WATER_GUN           369
#define MOVE_WATER_PULSE         370
#define MOVE_WATER_SPORT         371
#define MOVE_WATER_SPOUT         372
#define MOVE_WEATHER_BALL        373
#define MOVE_WHIRLPOOL           374
#define MOVE_WHIRLWIND           375
#define MOVE_WILD_CHARGE         376
#define MOVE_WILL_O_WISP         377
#define MOVE_WING_ATTACK         378
#define MOVE_WISH                379
#define MOVE_WITHDRAW            380
#define MOVE_WRAP                381
#define MOVE_X_SCISSOR           382
#define MOVE_YAWN                383
#define MOVE_ZAP_CANNON          384

#define MOVES_COUNT              385

// Used for checks for moves affected by Disable, Mimic, etc.
#define MOVE_UNAVAILABLE 0xFFFF

#define MOVETUTOR_MEGA_PUNCH    0
#define MOVETUTOR_SWORDS_DANCE  1
#define MOVETUTOR_MEGA_KICK     2
#define MOVETUTOR_BODY_SLAM     3
#define MOVETUTOR_DOUBLE_EDGE   4
#define MOVETUTOR_COUNTER       5
#define MOVETUTOR_SEISMIC_TOSS  6
#define MOVETUTOR_MIMIC         7
#define MOVETUTOR_METRONOME     8
#define MOVETUTOR_SOFT_BOILED   9
#define MOVETUTOR_DREAM_EATER  10
#define MOVETUTOR_THUNDER_WAVE 11
#define MOVETUTOR_EXPLOSION    12
#define MOVETUTOR_ROCK_SLIDE   13
#define MOVETUTOR_SUBSTITUTE   14
#define MOVETUTOR_FRENZY_PLANT 15
#define MOVETUTOR_BLAST_BURN   16
#define MOVETUTOR_HYDRO_CANNON 17

#endif  // GUARD_CONSTANTS_MOVES_H
