#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

#define MOVE_NONE                0
#define MOVE_ABSORB              1
#define MOVE_ACID                2
#define MOVE_ACID_ARMOR          3
#define MOVE_AERIAL_ACE          4
#define MOVE_AEROBLAST           5
#define MOVE_AGILITY             6
#define MOVE_AIR_CUTTER          7
#define MOVE_AMNESIA             8
#define MOVE_ANCIENT_POWER       9
#define MOVE_ARM_THRUST          10
#define MOVE_AROMATHERAPY        11
#define MOVE_ASSIST              12
#define MOVE_ASTONISH            13
#define MOVE_ATTRACT             14
#define MOVE_AURA_SPHERE         15
#define MOVE_AURORA_BEAM         16
#define MOVE_BARRAGE             17
#define MOVE_BARRIER             18
#define MOVE_BATON_PASS          19
#define MOVE_BEAT_UP             20
#define MOVE_BELLY_DRUM          21
#define MOVE_BIDE                22
#define MOVE_BIND                23
#define MOVE_BITE                24
#define MOVE_BLAST_BURN          25
#define MOVE_BLAZE_KICK          26
#define MOVE_BLIZZARD            27
#define MOVE_BLOCK               28
#define MOVE_BODY_SLAM           29
#define MOVE_BONEMERANG          30
#define MOVE_BONE_CLUB           31
#define MOVE_BONE_RUSH           32
#define MOVE_BOUNCE              33
#define MOVE_BRICK_BREAK         34
#define MOVE_BUBBLE              35
#define MOVE_BUBBLE_BEAM         36
#define MOVE_BUG_BUZZ            37
#define MOVE_BULK_UP             38
#define MOVE_BULLET_SEED         39
#define MOVE_CALM_MIND           40
#define MOVE_CAMOUFLAGE          41
#define MOVE_CHARGE              42
#define MOVE_CHARGE_BEAM         43
#define MOVE_CHARM               44
#define MOVE_CLAMP               45
#define MOVE_COMET_PUNCH         46
#define MOVE_CONFUSE_RAY         47
#define MOVE_CONFUSION           48
#define MOVE_CONSTRICT           49
#define MOVE_CONVERSION          50
#define MOVE_CONVERSION_2        51
#define MOVE_COSMIC_POWER        52
#define MOVE_COTTON_SPORE        53
#define MOVE_COUNTER             54
#define MOVE_COVET               55
#define MOVE_CRABHAMMER          56
#define MOVE_CROSS_CHOP          57
#define MOVE_CRUNCH              58
#define MOVE_CRUSH_CLAW          59
#define MOVE_CURSE               60
#define MOVE_CUT                 61
#define MOVE_DARK_PULSE          62
#define MOVE_DEFENSE_CURL        63
#define MOVE_DESTINY_BOND        64
#define MOVE_DETECT              65
#define MOVE_DIG                 66
#define MOVE_DISABLE             67
#define MOVE_DISARMING_CRY       68
#define MOVE_DIVE                69
#define MOVE_DIZZY_PUNCH         70
#define MOVE_DOOM_DESIRE         71
#define MOVE_DOUBLE_EDGE         72
#define MOVE_DOUBLE_KICK         73
#define MOVE_DOUBLE_SLAP         74
#define MOVE_DOUBLE_TEAM         75
#define MOVE_DRAGON_BREATH       76
#define MOVE_DRAGON_CLAW         77
#define MOVE_DRAGON_DANCE        78
#define MOVE_DRAGON_RAGE         79
#define MOVE_DRAGON_TAIL         80
#define MOVE_DRAIN_KISS          81
#define MOVE_DREAM_EATER         82
#define MOVE_DRILL_PECK          83
#define MOVE_DRILL_RUN           84
#define MOVE_DYNAMIC_PUNCH       85
#define MOVE_EARTHQUAKE          86
#define MOVE_EARTH_AURA          87
#define MOVE_EGG_BOMB            88
#define MOVE_EMBER               89
#define MOVE_ENCORE              90
#define MOVE_ENDEAVOR            91
#define MOVE_ENDURE              92
#define MOVE_ERUPTION            93
#define MOVE_EXPLOSION           94
#define MOVE_EXTRASENSORY        95
#define MOVE_EXTREME_SPEED       96
#define MOVE_FACADE              97
#define MOVE_FAKE_OUT            98
#define MOVE_FAKE_TEARS          99
#define MOVE_FALSE_SWIPE         100
#define MOVE_FEATHER_DANCE       101
#define MOVE_FEINT_ATTACK        102
#define MOVE_FIRE_BLAST          103
#define MOVE_FIRE_FANG           104
#define MOVE_FIRE_PUNCH          105
#define MOVE_FIRE_SPIN           106
#define MOVE_FISSURE             107
#define MOVE_FLAIL               108
#define MOVE_FLAMETHROWER        109
#define MOVE_FLAME_CHARGE        110
#define MOVE_FLAME_WHEEL         111
#define MOVE_FLASH               112
#define MOVE_FLASH_CANNON        113
#define MOVE_FLATTER             114
#define MOVE_FLY                 115
#define MOVE_FOCUS_BLAST         116
#define MOVE_FOCUS_ENERGY        117
#define MOVE_FOCUS_PUNCH         118
#define MOVE_FOLLOW_ME           119
#define MOVE_FORCE_PALM          120
#define MOVE_FORESIGHT           121
#define MOVE_FRENZY_PLANT        122
#define MOVE_FRUSTRATION         123
#define MOVE_FURY_ATTACK         124
#define MOVE_FURY_CUTTER         125
#define MOVE_FURY_SWIPES         126
#define MOVE_FUTURE_SIGHT        127
#define MOVE_GIGA_DRAIN          128
#define MOVE_GLARE               129
#define MOVE_GRASS_WHISTLE       130
#define MOVE_GROWL               131
#define MOVE_GROWTH              132
#define MOVE_GRUDGE              133
#define MOVE_GUILLOTINE          134
#define MOVE_GUST                135
#define MOVE_HAIL                136
#define MOVE_HARDEN              137
#define MOVE_HAZE                138
#define MOVE_HEADBUTT            139
#define MOVE_HEAD_SMASH          140
#define MOVE_HEAL_BELL           141
#define MOVE_HEAT_WAVE           142
#define MOVE_HELPING_HAND        143
#define MOVE_HIDDEN_POWER        144
#define MOVE_HI_JUMP_KICK        145
#define MOVE_HORN_ATTACK         146
#define MOVE_HORN_DRILL          147
#define MOVE_HOWL                148
#define MOVE_HYDRO_CANNON        149
#define MOVE_HYDRO_PUMP          150
#define MOVE_HYPER_BEAM          151
#define MOVE_HYPER_FANG          152
#define MOVE_HYPER_VOICE         153
#define MOVE_HYPNOSIS            154
#define MOVE_ICE_BALL            155
#define MOVE_ICE_BEAM            156
#define MOVE_ICE_FANG            157
#define MOVE_ICE_PUNCH           158
#define MOVE_ICICLE_SPEAR        159
#define MOVE_ICY_WIND            160
#define MOVE_IMPRISON            161
#define MOVE_INFESTATION         162
#define MOVE_INGRAIN             163
#define MOVE_IRON_DEFENSE        164
#define MOVE_IRON_HEAD           165
#define MOVE_IRON_TAIL           166
#define MOVE_JUMP_KICK           167
#define MOVE_KARATE_CHOP         168
#define MOVE_KINESIS             169
#define MOVE_KNOCK_OFF           170
#define MOVE_LAVA_PLUME          171
#define MOVE_LEAF_BLADE          172
#define MOVE_LEECH_LIFE          173
#define MOVE_LEECH_SEED          174
#define MOVE_LEER                175
#define MOVE_LICK                176
#define MOVE_LIGHT_SCREEN        177
#define MOVE_LOCK_ON             178
#define MOVE_LOW_KICK            179
#define MOVE_LULLABY_KISS        180
#define MOVE_LUSTER_PURGE        181
#define MOVE_MACH_PUNCH          182
#define MOVE_MAGICAL_LEAF        183
#define MOVE_MAGIC_COAT          184
#define MOVE_MAGNITUDE           185
#define MOVE_MEAN_LOOK           186
#define MOVE_MEDITATE            187
#define MOVE_MEGAHORN            188
#define MOVE_MEGA_DRAIN          189
#define MOVE_MEGA_KICK           190
#define MOVE_MEGA_PUNCH          191
#define MOVE_MEMENTO             192
#define MOVE_METAL_CLAW          193
#define MOVE_METAL_SOUND         194
#define MOVE_METEOR_MASH         195
#define MOVE_METRONOME           196
#define MOVE_MILK_DRINK          197
#define MOVE_MIMIC               198
#define MOVE_MIND_READER         199
#define MOVE_MINIMIZE            200
#define MOVE_MIRROR_COAT         201
#define MOVE_MIRROR_MOVE         202
#define MOVE_MIST                203
#define MOVE_MIST_BALL           204
#define MOVE_MOONBLAST           205
#define MOVE_MOONLIGHT           206
#define MOVE_MORNING_SUN         207
#define MOVE_MUDDY_WATER         208
#define MOVE_MUD_BOMB            209
#define MOVE_MUD_SHOT            210
#define MOVE_MUD_SLAP            211
#define MOVE_MUD_SPORT           212
#define MOVE_NATURE_POWER        213
#define MOVE_NEEDLE_ARM          214
#define MOVE_NIGHTMARE           215
#define MOVE_NIGHT_SHADE         216
#define MOVE_OCTAZOOKA           217
#define MOVE_ODOR_SLEUTH         218
#define MOVE_OUTRAGE             219
#define MOVE_OVERHEAT            220
#define MOVE_PAIN_SPLIT          221
#define MOVE_PAY_DAY             222
#define MOVE_PECK                223
#define MOVE_PERISH_SONG         224
#define MOVE_PETAL_DANCE         225
#define MOVE_PIN_MISSILE         226
#define MOVE_POISON_FANG         227
#define MOVE_POISON_GAS          228
#define MOVE_POISON_POWDER       229
#define MOVE_POISON_STING        230
#define MOVE_POISON_TAIL         231
#define MOVE_POUND               232
#define MOVE_POWDER_SNOW         233
#define MOVE_PRESENT             234
#define MOVE_PROTECT             235
#define MOVE_PSYBEAM             236
#define MOVE_PSYCHIC             237
#define MOVE_PSYCHO_BOOST        238
#define MOVE_PSYCH_UP            239
#define MOVE_PSYWAVE             240
#define MOVE_PURSUIT             241
#define MOVE_QUICK_ATTACK        242
#define MOVE_RAGE                243
#define MOVE_RAGE_POWDER         244
#define MOVE_RAIN_DANCE          245
#define MOVE_RAPID_SPIN          246
#define MOVE_RAZOR_LEAF          247
#define MOVE_RAZOR_WIND          248
#define MOVE_RECOVER             249
#define MOVE_RECYCLE             250
#define MOVE_REFLECT             251
#define MOVE_REFRESH             252
#define MOVE_REST                253
#define MOVE_RETURN              254
#define MOVE_REVENGE             255
#define MOVE_REVERSAL            256
#define MOVE_ROAR                257
#define MOVE_ROCK_BLAST          258
#define MOVE_ROCK_SLIDE          259
#define MOVE_ROCK_SMASH          260
#define MOVE_ROCK_THROW          261
#define MOVE_ROCK_TOMB           262
#define MOVE_ROLE_PLAY           263
#define MOVE_ROLLING_KICK        264
#define MOVE_ROLLOUT             265
#define MOVE_SACRED_FIRE         266
#define MOVE_SAFEGUARD           267
#define MOVE_SANDSTORM           268
#define MOVE_SAND_ATTACK         269
#define MOVE_SAND_TOMB           270
#define MOVE_SCARY_FACE          271
#define MOVE_SCRATCH             272
#define MOVE_SCREECH             273
#define MOVE_SECRET_POWER        274
#define MOVE_SEISMIC_TOSS        275
#define MOVE_SELF_DESTRUCT       276
#define MOVE_SHADOW_BALL         277
#define MOVE_SHADOW_PUNCH        278
#define MOVE_SHARPEN             279
#define MOVE_SHEER_COLD          280
#define MOVE_SHOCK_WAVE          281
#define MOVE_SIGNAL_BEAM         282
#define MOVE_SILVER_WIND         283
#define MOVE_SING                284
#define MOVE_SKETCH              285
#define MOVE_SKILL_SWAP          286
#define MOVE_SKULL_BASH          287
#define MOVE_SKY_ATTACK          288
#define MOVE_SKY_UPPERCUT        289
#define MOVE_SLACK_OFF           290
#define MOVE_SLAM                291
#define MOVE_SLASH               292
#define MOVE_SLEEP_POWDER        293
#define MOVE_SLEEP_TALK          294
#define MOVE_SLUDGE              295
#define MOVE_SLUDGE_BOMB         296
#define MOVE_SMELLING_SALT       297
#define MOVE_SMOG                298
#define MOVE_SMOKESCREEN         299
#define MOVE_SNARL               300
#define MOVE_SNATCH              301
#define MOVE_SNORE               302
#define MOVE_SOFT_BOILED         303
#define MOVE_SOLAR_BEAM          304
#define MOVE_SONIC_BOOM          305
#define MOVE_SPARK               306
#define MOVE_SPIDER_WEB          307
#define MOVE_SPIKES              308
#define MOVE_SPIKE_CANNON        309
#define MOVE_SPITE               310
#define MOVE_SPIT_UP             311
#define MOVE_SPLASH              312
#define MOVE_SPORE               313
#define MOVE_STEEL_WING          314
#define MOVE_STOCKPILE           315
#define MOVE_STOMP               316
#define MOVE_STONE_SURGE         317
#define MOVE_STRENGTH            318
#define MOVE_STRING_SHOT         319
#define MOVE_STRUGGLE            320
#define MOVE_STRUGGLE_BUG        321
#define MOVE_STUN_SPORE          322
#define MOVE_SUBMISSION          323
#define MOVE_SUBSTITUTE          324
#define MOVE_SUNNY_DAY           325
#define MOVE_SUPERPOWER          326
#define MOVE_SUPERSONIC          327
#define MOVE_SUPER_FANG          328
#define MOVE_SURF                329
#define MOVE_SWAGGER             330
#define MOVE_SWALLOW             331
#define MOVE_SWEET_KISS          332
#define MOVE_SWEET_SCENT         333
#define MOVE_SWIFT               334
#define MOVE_SWORDS_DANCE        335
#define MOVE_SYNTHESIS           336
#define MOVE_TACKLE              337
#define MOVE_TAIL_GLOW           338
#define MOVE_TAIL_WHIP           339
#define MOVE_TAKE_DOWN           340
#define MOVE_TAUNT               341
#define MOVE_TEETER_DANCE        342
#define MOVE_TELEPORT            343
#define MOVE_THIEF               344
#define MOVE_THRASH              345
#define MOVE_THUNDER             346
#define MOVE_THUNDERBOLT         347
#define MOVE_THUNDER_FANG        348
#define MOVE_THUNDER_PUNCH       349
#define MOVE_THUNDER_SHOCK       350
#define MOVE_THUNDER_WAVE        351
#define MOVE_TICKLE              352
#define MOVE_TORMENT             353
#define MOVE_TOXIC               354
#define MOVE_TRANSFORM           355
#define MOVE_TRICK               356
#define MOVE_TRIPLE_KICK         357
#define MOVE_TRI_ATTACK          358
#define MOVE_TWINEEDLE           359
#define MOVE_TWISTER             360
#define MOVE_UPROAR              361
#define MOVE_U_TURN              362
#define MOVE_VENOM_JAB           363
#define MOVE_VICE_GRIP           364
#define MOVE_VINE_WHIP           365
#define MOVE_VITAL_THROW         366
#define MOVE_VOLT_SWITCH         367
#define MOVE_VOLT_TACKLE         368
#define MOVE_WATERFALL           369
#define MOVE_WATER_GUN           370
#define MOVE_WATER_PULSE         371
#define MOVE_WATER_SPORT         372
#define MOVE_WATER_SPOUT         373
#define MOVE_WEATHER_BALL        374
#define MOVE_WHIRLPOOL           375
#define MOVE_WHIRLWIND           376
#define MOVE_WILD_CHARGE         377
#define MOVE_WILL_O_WISP         378
#define MOVE_WING_ATTACK         379
#define MOVE_WISH                380
#define MOVE_WITHDRAW            381
#define MOVE_WRAP                382
#define MOVE_X_SCISSOR           383
#define MOVE_YAWN                384
#define MOVE_ZAP_CANNON          385

#define MOVES_COUNT              386

// Used for checks for moves affected by Disable, Mimic, etc.
#define MOVE_UNAVAILABLE 0xFFFF

#define MOVETUTOR_MEGA_PUNCH    0
#define MOVETUTOR_SWORDS_DANCE  1
#define MOVETUTOR_MEGA_KICK     2
#define MOVETUTOR_BODY_SLAM     3
#define MOVETUTOR_DOUBLE_EDGE   4
#define MOVETUTOR_COUNTER       5
#define MOVETUTOR_SEISMIC_TOSS  6
#define MOVETUTOR_MIMIC         7
#define MOVETUTOR_METRONOME     8
#define MOVETUTOR_SOFT_BOILED   9
#define MOVETUTOR_DREAM_EATER  10
#define MOVETUTOR_THUNDER_WAVE 11
#define MOVETUTOR_EXPLOSION    12
#define MOVETUTOR_ROCK_SLIDE   13
#define MOVETUTOR_SUBSTITUTE   14
#define MOVETUTOR_FRENZY_PLANT 15
#define MOVETUTOR_BLAST_BURN   16
#define MOVETUTOR_HYDRO_CANNON 17

#endif  // GUARD_CONSTANTS_MOVES_H
