#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

#define MOVE_NONE                0
#define MOVE_ABSORB              1
#define MOVE_ACID                2
#define MOVE_ACID_ARMOR          3
#define MOVE_AERIAL_ACE          4
#define MOVE_AEROBLAST           5
#define MOVE_AGILITY             6
#define MOVE_AIR_CUTTER          7
#define MOVE_AMNESIA             8
#define MOVE_ANCIENT_POWER       9
#define MOVE_ARM_THRUST          10
#define MOVE_AROMATHERAPY        11
#define MOVE_ASSIST              12
#define MOVE_ASTONISH            13
#define MOVE_ATTRACT             14
#define MOVE_AURORA_BEAM         15
#define MOVE_BARRAGE             16
#define MOVE_BARRIER             17
#define MOVE_BATON_PASS          18
#define MOVE_BEAT_UP             19
#define MOVE_BELLY_DRUM          20
#define MOVE_BIDE                21
#define MOVE_BIND                22
#define MOVE_BITE                23
#define MOVE_BLAST_BURN          24
#define MOVE_BLAZE_KICK          25
#define MOVE_BLIZZARD            26
#define MOVE_BLOCK               27
#define MOVE_BODY_SLAM           28
#define MOVE_BONEMERANG          29
#define MOVE_BONE_CLUB           30
#define MOVE_BONE_RUSH           31
#define MOVE_BOUNCE              32
#define MOVE_BRICK_BREAK         33
#define MOVE_BUBBLE              34
#define MOVE_BUBBLE_BEAM         35
#define MOVE_BUG_BUZZ            36
#define MOVE_BULK_UP             37
#define MOVE_BULLET_SEED         38
#define MOVE_CALM_MIND           39
#define MOVE_CAMOUFLAGE          40
#define MOVE_CHARGE              41
#define MOVE_CHARM               42
#define MOVE_CLAMP               43
#define MOVE_COMET_PUNCH         44
#define MOVE_CONFUSE_RAY         45
#define MOVE_CONFUSION           46
#define MOVE_CONSTRICT           47
#define MOVE_CONVERSION          48
#define MOVE_CONVERSION_2        49
#define MOVE_COSMIC_POWER        50
#define MOVE_COTTON_SPORE        51
#define MOVE_COUNTER             52
#define MOVE_COVET               53
#define MOVE_CRABHAMMER          54
#define MOVE_CROSS_CHOP          55
#define MOVE_CRUNCH              56
#define MOVE_CRUSH_CLAW          57
#define MOVE_CURSE               58
#define MOVE_CUT                 59
#define MOVE_DARK_PULSE          60
#define MOVE_DEFENSE_CURL        61
#define MOVE_DESTINY_BOND        62
#define MOVE_DETECT              63
#define MOVE_DIG                 64
#define MOVE_DISABLE             65
#define MOVE_DIVE                66
#define MOVE_DIZZY_PUNCH         67
#define MOVE_DOOM_DESIRE         68
#define MOVE_DOUBLE_EDGE         69
#define MOVE_DOUBLE_KICK         70
#define MOVE_DOUBLE_SLAP         71
#define MOVE_DOUBLE_TEAM         72
#define MOVE_DRAGON_BREATH       73
#define MOVE_DRAGON_CLAW         74
#define MOVE_DRAGON_DANCE        75
#define MOVE_DRAGON_RAGE         76
#define MOVE_DREAM_EATER         77
#define MOVE_DRILL_PECK          78
#define MOVE_DRILL_RUN           79
#define MOVE_DYNAMIC_PUNCH       80
#define MOVE_EARTHQUAKE          81
#define MOVE_EARTH_AURA          82
#define MOVE_EGG_BOMB            83
#define MOVE_EMBER               84
#define MOVE_ENCORE              85
#define MOVE_ENDEAVOR            86
#define MOVE_ENDURE              87
#define MOVE_ERUPTION            88
#define MOVE_EXPLOSION           89
#define MOVE_EXTRASENSORY        90
#define MOVE_EXTREME_SPEED       91
#define MOVE_FACADE              92
#define MOVE_FAKE_OUT            93
#define MOVE_FAKE_TEARS          94
#define MOVE_FALSE_SWIPE         95
#define MOVE_FEATHER_DANCE       96
#define MOVE_FEINT_ATTACK        97
#define MOVE_FIRE_BLAST          98
#define MOVE_FIRE_PUNCH          99
#define MOVE_FIRE_SPIN           100
#define MOVE_FISSURE             101
#define MOVE_FLAIL               102
#define MOVE_FLAMETHROWER        103
#define MOVE_FLAME_WHEEL         104
#define MOVE_FLASH               105
#define MOVE_FLATTER             106
#define MOVE_FLY                 107
#define MOVE_FOCUS_ENERGY        108
#define MOVE_FOCUS_PUNCH         109
#define MOVE_FOLLOW_ME           110
#define MOVE_FORESIGHT           111
#define MOVE_FRENZY_PLANT        112
#define MOVE_FRUSTRATION         113
#define MOVE_FURY_ATTACK         114
#define MOVE_FURY_CUTTER         115
#define MOVE_FURY_SWIPES         116
#define MOVE_FUTURE_SIGHT        117
#define MOVE_GIGA_DRAIN          118
#define MOVE_GLARE               119
#define MOVE_GRASS_WHISTLE       120
#define MOVE_GROWL               121
#define MOVE_GROWTH              122
#define MOVE_GRUDGE              123
#define MOVE_GUILLOTINE          124
#define MOVE_GUST                125
#define MOVE_HAIL                126
#define MOVE_HARDEN              127
#define MOVE_HAZE                128
#define MOVE_HEADBUTT            129
#define MOVE_HEAL_BELL           130
#define MOVE_HEAT_WAVE           131
#define MOVE_HELPING_HAND        132
#define MOVE_HIDDEN_POWER        133
#define MOVE_HI_JUMP_KICK        134
#define MOVE_HORN_ATTACK         135
#define MOVE_HORN_DRILL          136
#define MOVE_HOWL                137
#define MOVE_HYDRO_CANNON        138
#define MOVE_HYDRO_PUMP          139
#define MOVE_HYPER_BEAM          140
#define MOVE_HYPER_FANG          141
#define MOVE_HYPER_VOICE         142
#define MOVE_HYPNOSIS            143
#define MOVE_ICE_BALL            144
#define MOVE_ICE_BEAM            145
#define MOVE_ICE_PUNCH           146
#define MOVE_ICICLE_SPEAR        147
#define MOVE_ICY_WIND            148
#define MOVE_IMPRISON            149
#define MOVE_INFESTATION         150
#define MOVE_INGRAIN             151
#define MOVE_IRON_DEFENSE        152
#define MOVE_IRON_TAIL           153
#define MOVE_JUMP_KICK           154
#define MOVE_KARATE_CHOP         155
#define MOVE_KINESIS             156
#define MOVE_KNOCK_OFF           157
#define MOVE_LEAF_BLADE          158
#define MOVE_LEECH_LIFE          159
#define MOVE_LEECH_SEED          160
#define MOVE_LEER                161
#define MOVE_LICK                162
#define MOVE_LIGHT_SCREEN        163
#define MOVE_LOCK_ON             164
#define MOVE_LOVELY_KISS         165
#define MOVE_LOW_KICK            166
#define MOVE_LUSTER_PURGE        167
#define MOVE_MACH_PUNCH          168
#define MOVE_MAGICAL_LEAF        169
#define MOVE_MAGIC_COAT          170
#define MOVE_MAGNITUDE           171
#define MOVE_MEAN_LOOK           172
#define MOVE_MEDITATE            173
#define MOVE_MEGAHORN            174
#define MOVE_MEGA_DRAIN          175
#define MOVE_MEGA_KICK           176
#define MOVE_MEGA_PUNCH          177
#define MOVE_MEMENTO             178
#define MOVE_METAL_CLAW          179
#define MOVE_METAL_SOUND         180
#define MOVE_METEOR_MASH         181
#define MOVE_METRONOME           182
#define MOVE_MILK_DRINK          183
#define MOVE_MIMIC               184
#define MOVE_MIND_READER         185
#define MOVE_MINIMIZE            186
#define MOVE_MIRROR_COAT         187
#define MOVE_MIRROR_MOVE         188
#define MOVE_MIST                189
#define MOVE_MIST_BALL           190
#define MOVE_MOONLIGHT           191
#define MOVE_MORNING_SUN         192
#define MOVE_MUDDY_WATER         193
#define MOVE_MUD_BOMB            194
#define MOVE_MUD_SHOT            195
#define MOVE_MUD_SLAP            196
#define MOVE_MUD_SPORT           197
#define MOVE_NATURE_POWER        198
#define MOVE_NEEDLE_ARM          199
#define MOVE_NIGHTMARE           200
#define MOVE_NIGHT_SHADE         201
#define MOVE_OCTAZOOKA           202
#define MOVE_ODOR_SLEUTH         203
#define MOVE_OUTRAGE             204
#define MOVE_OVERHEAT            205
#define MOVE_PAIN_SPLIT          206
#define MOVE_PAY_DAY             207
#define MOVE_PECK                208
#define MOVE_PERISH_SONG         209
#define MOVE_PETAL_DANCE         210
#define MOVE_PIN_MISSILE         211
#define MOVE_POISON_FANG         212
#define MOVE_POISON_GAS          213
#define MOVE_POISON_POWDER       214
#define MOVE_POISON_STING        215
#define MOVE_POISON_TAIL         216
#define MOVE_POUND               217
#define MOVE_POWDER_SNOW         218
#define MOVE_PRESENT             219
#define MOVE_PROTECT             220
#define MOVE_PSYBEAM             221
#define MOVE_PSYCHIC             222
#define MOVE_PSYCHO_BOOST        223
#define MOVE_PSYCH_UP            224
#define MOVE_PSYWAVE             225
#define MOVE_PURSUIT             226
#define MOVE_QUICK_ATTACK        227
#define MOVE_RAGE                228
#define MOVE_RAGE_POWDER         229
#define MOVE_RAIN_DANCE          230
#define MOVE_RAPID_SPIN          231
#define MOVE_RAZOR_LEAF          232
#define MOVE_RAZOR_WIND          233
#define MOVE_RECOVER             234
#define MOVE_RECYCLE             235
#define MOVE_REFLECT             236
#define MOVE_REFRESH             237
#define MOVE_REST                238
#define MOVE_RETURN              239
#define MOVE_REVENGE             240
#define MOVE_REVERSAL            241
#define MOVE_ROAR                242
#define MOVE_ROCK_BLAST          243
#define MOVE_ROCK_SLIDE          244
#define MOVE_ROCK_SMASH          245
#define MOVE_ROCK_THROW          246
#define MOVE_ROCK_TOMB           247
#define MOVE_ROLE_PLAY           248
#define MOVE_ROLLING_KICK        249
#define MOVE_ROLLOUT             250
#define MOVE_SACRED_FIRE         251
#define MOVE_SAFEGUARD           252
#define MOVE_SANDSTORM           253
#define MOVE_SAND_ATTACK         254
#define MOVE_SAND_TOMB           255
#define MOVE_SCARY_FACE          256
#define MOVE_SCRATCH             257
#define MOVE_SCREECH             258
#define MOVE_SECRET_POWER        259
#define MOVE_SEISMIC_TOSS        260
#define MOVE_SELF_DESTRUCT       261
#define MOVE_SHADOW_BALL         262
#define MOVE_SHADOW_PUNCH        263
#define MOVE_SHARPEN             264
#define MOVE_SHEER_COLD          265
#define MOVE_SHOCK_WAVE          266
#define MOVE_SIGNAL_BEAM         267
#define MOVE_SILVER_WIND         268
#define MOVE_SING                269
#define MOVE_SKETCH              270
#define MOVE_SKILL_SWAP          271
#define MOVE_SKULL_BASH          272
#define MOVE_SKY_ATTACK          273
#define MOVE_SKY_UPPERCUT        274
#define MOVE_SLACK_OFF           275
#define MOVE_SLAM                276
#define MOVE_SLASH               277
#define MOVE_SLEEP_POWDER        278
#define MOVE_SLEEP_TALK          279
#define MOVE_SLUDGE              280
#define MOVE_SLUDGE_BOMB         281
#define MOVE_SMELLING_SALT       282
#define MOVE_SMOG                283
#define MOVE_SMOKESCREEN         284
#define MOVE_SNARL               285
#define MOVE_SNATCH              286
#define MOVE_SNORE               287
#define MOVE_SOFT_BOILED         288
#define MOVE_SOLAR_BEAM          289
#define MOVE_SONIC_BOOM          290
#define MOVE_SPARK               291
#define MOVE_SPIDER_WEB          292
#define MOVE_SPIKES              293
#define MOVE_SPIKE_CANNON        294
#define MOVE_SPITE               295
#define MOVE_SPIT_UP             296
#define MOVE_SPLASH              297
#define MOVE_SPORE               298
#define MOVE_STEEL_WING          299
#define MOVE_STOCKPILE           300
#define MOVE_STOMP               301
#define MOVE_STRENGTH            302
#define MOVE_STRING_SHOT         303
#define MOVE_STRUGGLE            304
#define MOVE_STRUGGLE_BUG        305
#define MOVE_STUN_SPORE          306
#define MOVE_SUBMISSION          307
#define MOVE_SUBSTITUTE          308
#define MOVE_SUNNY_DAY           309
#define MOVE_SUPERPOWER          310
#define MOVE_SUPERSONIC          311
#define MOVE_SUPER_FANG          312
#define MOVE_SURF                313
#define MOVE_SWAGGER             314
#define MOVE_SWALLOW             315
#define MOVE_SWEET_KISS          316
#define MOVE_SWEET_SCENT         317
#define MOVE_SWIFT               318
#define MOVE_SWORDS_DANCE        319
#define MOVE_SYNTHESIS           320
#define MOVE_TACKLE              321
#define MOVE_TAIL_GLOW           322
#define MOVE_TAIL_WHIP           323
#define MOVE_TAKE_DOWN           324
#define MOVE_TAUNT               325
#define MOVE_TEETER_DANCE        326
#define MOVE_TELEPORT            327
#define MOVE_THIEF               328
#define MOVE_THRASH              329
#define MOVE_THUNDER             330
#define MOVE_THUNDERBOLT         331
#define MOVE_THUNDER_PUNCH       332
#define MOVE_THUNDER_SHOCK       333
#define MOVE_THUNDER_WAVE        334
#define MOVE_TICKLE              335
#define MOVE_TORMENT             336
#define MOVE_TOXIC               337
#define MOVE_TRANSFORM           338
#define MOVE_TRICK               339
#define MOVE_TRIPLE_KICK         340
#define MOVE_TRI_ATTACK          341
#define MOVE_TWINEEDLE           342
#define MOVE_TWISTER             343
#define MOVE_UPROAR              344
#define MOVE_U_TURN              345
#define MOVE_VICE_GRIP           346
#define MOVE_VINE_WHIP           347
#define MOVE_VITAL_THROW         348
#define MOVE_VOLT_TACKLE         349
#define MOVE_WATERFALL           350
#define MOVE_WATER_GUN           351
#define MOVE_WATER_PULSE         352
#define MOVE_WATER_SPORT         353
#define MOVE_WATER_SPOUT         354
#define MOVE_WEATHER_BALL        355
#define MOVE_WHIRLPOOL           356
#define MOVE_WHIRLWIND           357
#define MOVE_WILL_O_WISP         358
#define MOVE_WING_ATTACK         359
#define MOVE_WISH                360
#define MOVE_WITHDRAW            361
#define MOVE_WRAP                362
#define MOVE_X_SCISSOR           363
#define MOVE_YAWN                364
#define MOVE_ZAP_CANNON          365

#define MOVES_COUNT              366

// Used for checks for moves affected by Disable, Mimic, etc.
#define MOVE_UNAVAILABLE 0xFFFF

#define MOVETUTOR_MEGA_PUNCH    0
#define MOVETUTOR_SWORDS_DANCE  1
#define MOVETUTOR_MEGA_KICK     2
#define MOVETUTOR_BODY_SLAM     3
#define MOVETUTOR_DOUBLE_EDGE   4
#define MOVETUTOR_COUNTER       5
#define MOVETUTOR_SEISMIC_TOSS  6
#define MOVETUTOR_MIMIC         7
#define MOVETUTOR_METRONOME     8
#define MOVETUTOR_SOFT_BOILED   9
#define MOVETUTOR_DREAM_EATER  10
#define MOVETUTOR_THUNDER_WAVE 11
#define MOVETUTOR_EXPLOSION    12
#define MOVETUTOR_ROCK_SLIDE   13
#define MOVETUTOR_SUBSTITUTE   14
#define MOVETUTOR_FRENZY_PLANT 15
#define MOVETUTOR_BLAST_BURN   16
#define MOVETUTOR_HYDRO_CANNON 17

#endif  // GUARD_CONSTANTS_MOVES_H
