#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Absorb[]          = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_AcidArmor[]       = _("The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.");
const u8 gMoveDescription_Acid[]            = _("Foes are sprayed\nwith a harsh acid.\nSuper effective on\nSTEEL-types.");
const u8 gMoveDescription_AerialAce[]       = _("An extremely fast\nattack against one\ntarget. It can't be\nevaded.");
const u8 gMoveDescription_Aeroblast[]       = _("A vortex of air is\nshot at the foe.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Agility[]         = _("The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.");
const u8 gMoveDescription_AirCutter[]       = _("The foe is hit with\nrazor-like wind.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Amnesia[]         = _("Forgets about\nsomething and\nsharply raises\nSP. DEF.");
const u8 gMoveDescription_AncientPower[]    = _("An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.");
const u8 gMoveDescription_ArmThrust[]       = _("A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.");
const u8 gMoveDescription_Aromatherapy[]    = _("A soothing scent is\nreleased to heal\nall status problems\nin the user's party.");
const u8 gMoveDescription_Assist[]          = _("The user randomly\npicks and uses a\nmove of an allied\nPOKéMON.");
const u8 gMoveDescription_Astonish[]        = _("An attack using a\nstartling shout.\nIt also may make\nthe foe flinch.");
const u8 gMoveDescription_Attract[]         = _("If it is the other\ngender, the foe is\nmade infatuated and\nunlikely to attack.");
const u8 gMoveDescription_AuraSphere[]      = _("The user looses a\nblast of aura from\ndeep within. It\ncan't be evaded.");
const u8 gMoveDescription_AuroraBeam[]      = _("A rainbow-colored\nattack beam.\nIt may lower the\nfoe's ATTACK stat.");
const u8 gMoveDescription_Barrage[]         = _("Hurls objects using\nthe power of the\nmind, striking two\nto five times.");
const u8 gMoveDescription_Barrier[]         = _("The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.");
const u8 gMoveDescription_BatonPass[]       = _("The user switches\nout, passing along\nany stat changes\nto the new battler.");
const u8 gMoveDescription_BeatUp[]          = _("All party POKéMON\njoin in the attack.\nThe more allies,\nthe more damage.");
const u8 gMoveDescription_BellyDrum[]       = _("The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.");
const u8 gMoveDescription_Bide[]            = _("The user endures\nattacks for two\nturns, then strikes\nback double.");
const u8 gMoveDescription_Bind[]            = _("A long body or\ntentacles are used\nto bind the foe for\ntwo to five turns.");
const u8 gMoveDescription_Bite[]            = _("The user bites with\nvicious fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_BlastBurn[]       = _("The foe is hit with\na huge explosion.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_BlazeKick[]       = _("The user delivers a\nfiery kick that has\na high critical-hit\nratio.");
const u8 gMoveDescription_Blizzard[]        = _("The foe is blasted\nwith a blizzard.\nIt may leave the\nfoe with frostbite.");
const u8 gMoveDescription_Block[]           = _("The user blocks the\nfoe's way with arms\nspread wide to\nprevent escape.");
const u8 gMoveDescription_BodySlam[]        = _("The user drops its\nfull body on the\nfoe. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_BoneClub[]        = _("Clubs the foe with\na conjured bone\nweapon. May make\nthe foe flinch.");
const u8 gMoveDescription_BoneRush[]        = _("The user attacks\nwith a conjured\nbone two to five\ntimes.");
const u8 gMoveDescription_Bonemerang[]      = _("The user hits the\nfoe twice with a\nconjured piece of\nbone.");
const u8 gMoveDescription_Bounce[]          = _("The user bounces\non the foe on the\n2nd turn. It may\nparalyze the foe.");
const u8 gMoveDescription_BrickBreak[]      = _("An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.");
const u8 gMoveDescription_BubbleBeam[]      = _("A spray of bubbles\nstrikes the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_Bubble[]          = _("A spray of bubbles\nhits the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_BugBuzz[]         = _("The user vibrates\nits wings to create\npainful noise. It\nmay lower SP. DEF.");
const u8 gMoveDescription_BulkUp[]          = _("The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.");
const u8 gMoveDescription_BulletSeed[]      = _("The user shoots\nseeds at the foe.\nTwo to five seeds\nare shot at once.");
const u8 gMoveDescription_CalmMind[]        = _("The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.");
const u8 gMoveDescription_Camouflage[]      = _("Alters the user's\ntype depending on\nthe location's\nterrain.");
const u8 gMoveDescription_Charge[]          = _("The user charges\npower, raising SP.\nDEF and boosting\nELECTRIC moves.");
const u8 gMoveDescription_ChargeBeam[]      = _("The user fires a\nconcentrated laser.\nAlso raises the\nuser's SP. ATK.");
const u8 gMoveDescription_Charm[]           = _("The foe is charmed\nby the user's cute\nappeals, sharply\ncutting its ATTACK.");
const u8 gMoveDescription_Clamp[]           = _("The foe is clamped\nand squeezed by\nthe user's shell for\ntwo to five turns.");
const u8 gMoveDescription_CometPunch[]      = _("The foe is hit with\na flurry of punches\nthat strike two to\nfive times.");
const u8 gMoveDescription_ConfuseRay[]      = _("The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.");
const u8 gMoveDescription_Confusion[]       = _("A weak telekinetic\nattack that may\nalso leave the foe\nconfused.");
const u8 gMoveDescription_Constrict[]       = _("The foe is attacked\nwith long tentacles\nor vines. It may\nlower SPEED.");
const u8 gMoveDescription_Conversion2[]     = _("The user changes\ntype to make itself\nresistant to the\nlast attack it took.");
const u8 gMoveDescription_Conversion[]      = _("The user changes\nits type to match\nthe type of one of\nits moves.");
const u8 gMoveDescription_CosmicPower[]     = _("The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.");
const u8 gMoveDescription_CottonSpore[]     = _("Cotton-like spores\ncling to the foe,\nsharply reducing\nits SPEED stat.");
const u8 gMoveDescription_Counter[]         = _("A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.");
const u8 gMoveDescription_Covet[]           = _("A cutely executed\nattack that also\nsteals the foe's\nhold item.");
const u8 gMoveDescription_Crabhammer[]      = _("A large pincer is\nused to hammer the\nfoe. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_CrossChop[]       = _("The foe is hit with\ndouble chops.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Crunch[]          = _("The foe is crunched\nwith sharp fangs.\nIt may lower the\nfoe's DEF.");
const u8 gMoveDescription_CrushClaw[]       = _("The foe is attacked\nwith sharp claws.\nIt may also lower\nthe foe's DEFENSE.");
const u8 gMoveDescription_Curse[]           = _("A move that works\ndifferently for the\nGHOST-type and all\nthe other types.");
const u8 gMoveDescription_Cut[]             = _("Slices the foe with\nsharp blades/claws.\nSuper effective on\nGRASS-types.");
const u8 gMoveDescription_DarkPulse[]       = _("The user releases\ntheir ill intent as\nan aura. May make\nthe foe flinch.");
const u8 gMoveDescription_DefenseCurl[]     = _("The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.");
const u8 gMoveDescription_DestinyBond[]     = _("If the user faints,\nthe foe delivering\nthe final hit also\nfaints.");
const u8 gMoveDescription_Detect[]          = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_Dig[]             = _("An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.");
const u8 gMoveDescription_Disable[]         = _("For a few turns,\nit prevents the foe\nfrom using the move\nit last used.");
const u8 gMoveDescription_DisarmingCry[]    = _("The user lets out\na sweet cry that\nis certain to hit\nfirst.");
const u8 gMoveDescription_Dive[]            = _("The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.");
const u8 gMoveDescription_DizzyPunch[]      = _("The foe is hit with\na rhythmic punch\nthat may leave it\nconfused.");
const u8 gMoveDescription_DoomDesire[]      = _("A move that attacks\nthe foe with a\nblast of light two\nturns after use.");
const u8 gMoveDescription_DoubleEdge[]      = _("A reckless, life-\nrisking tackle that\nalso hurts the user\na little.");
const u8 gMoveDescription_DoubleKick[]      = _("Two legs are used\nto quickly kick the\nfoe twice in one\nturn.");
const u8 gMoveDescription_DoubleSlap[]      = _("The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times.");
const u8 gMoveDescription_DoubleTeam[]      = _("The user creates\nillusory copies of\nitself to raise its\nevasiveness.");
const u8 gMoveDescription_DragonBreath[]    = _("The foe is hit with\nan incredible blast\nof breath that may\nalso paralyze.");
const u8 gMoveDescription_DragonClaw[]      = _("Sharp, huge claws\nhook and slash the\nfoe. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DragonDance[]     = _("A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.");
const u8 gMoveDescription_DragonRage[]      = _("A terrible energy\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_DragonTail[]      = _("The foe is knocked\naway and forced to\nswitch out with a\nparty member.");
const u8 gMoveDescription_DrainKiss[]       = _("Drains life with a\nkiss. Restores the\nuser's HP by half\nthe damage dealt.");
const u8 gMoveDescription_DreamEater[]      = _("Absorbs half the\ndamage it inflicted\non a sleeping foe\nto restore HP.");
const u8 gMoveDescription_DrillPeck[]       = _("A corkscrewing\nattack with the\nsharp beak acting\nas a drill.");
const u8 gMoveDescription_DrillRun[]        = _("The user spins like\na drill and tackles\nthe foe. Has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DynamicPunch[]    = _("The foe is punched\nwith the user's full\npower. It confuses\nthe foe if it hits.");
const u8 gMoveDescription_Earthquake[]      = _("An earthquake that\nstrikes all POKéMON\nin battle excluding\nthe user.");
const u8 gMoveDescription_EarthAura[]       = _("Wields the energy\nof the earth. The\nuser's SP. ATK\nfalls sharply.");
const u8 gMoveDescription_EggBomb[]         = _("A large egg is\nhurled with great\nforce at the foe to\ninflict damage.");
const u8 gMoveDescription_Ember[]           = _("The foe is attacked\nwith small flames.\nThe foe may suffer\na burn.");
const u8 gMoveDescription_Encore[]          = _("Makes the foe use\nthe move it last\nused repeatedly for\ntwo to six turns.");
const u8 gMoveDescription_Endeavor[]        = _("Gains power the\nfewer HP the user\nhas compared with\nthe foe.");
const u8 gMoveDescription_Endure[]          = _("The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.");
const u8 gMoveDescription_Eruption[]        = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_Explosion[]       = _("The user explodes\nto inflict terrible\ndamage even while\nfainting itself.");
const u8 gMoveDescription_Extrasensory[]    = _("The user attacks\nwith an odd power\nthat may make the\nfoe flinch.");
const u8 gMoveDescription_ExtremeSpeed[]    = _("A blindingly speedy\ncharge attack that\nalways goes before\nany other.");
const u8 gMoveDescription_Facade[]          = _("An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.");
const u8 gMoveDescription_FakeOut[]         = _("An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.");
const u8 gMoveDescription_FakeTears[]       = _("The user feigns\ncrying to sharply\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_FalseSwipe[]      = _("A restrained attack\nthat always leaves\nthe foe with at\nleast 1 HP.");
const u8 gMoveDescription_FeatherDance[]    = _("The foe is covered\nwith a mass of down\nthat sharply cuts\nthe ATTACK stat.");
const u8 gMoveDescription_FeintAttack[]     = _("The user draws up\nclose to the foe\ndisarmingly, then\nhits without fail.");
const u8 gMoveDescription_FireBlast[]       = _("The foe is hit with\nan intense flame.\nIt may leave the\ntarget with a burn.");
const u8 gMoveDescription_FireFang[]        = _("Bites the foe with\nfire infused fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_FirePunch[]       = _("The foe is punched\nwith a fiery fist.\nIt may leave the\nfoe with a burn.");
const u8 gMoveDescription_FireSpin[]        = _("The foe is trapped\nin an intense spiral\nof fire that rages\ntwo to five turns.");
const u8 gMoveDescription_Fissure[]         = _("The foe is dropped\ninto a fissure.\nThe foe faints if it\nhits.");
const u8 gMoveDescription_Flail[]           = _("A desperate attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_FlameCharge[]     = _("The user is cloaked\nin fire and rushes\nthe foe. Raises the\nuser's SPEED.");
const u8 gMoveDescription_FlameWheel[]      = _("The user attacks\nand reverses course\nto switch out with\na party member.");
const u8 gMoveDescription_Flamethrower[]    = _("The foe is scorched\nwith intense flames.\nThe foe may suffer\na burn.");
const u8 gMoveDescription_Flash[]           = _("Releases a brief\nburst of blinding\nlight. It is certain\nto strike first.");
const u8 gMoveDescription_Flatter[]         = _("Flattery is used to\nconfuse the foe,\nbut its SP. ATK\nalso rises.");
const u8 gMoveDescription_Fly[]             = _("A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.");
const u8 gMoveDescription_FocusBlast[]      = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_FocusEnergy[]     = _("The user focuses to\nup its critical-hit\nratio and regain HP\nfor five turns.");
const u8 gMoveDescription_FocusPunch[]      = _("An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.");
const u8 gMoveDescription_FollowMe[]        = _("The user draws\nattention to itself,\nmaking foes attack\nonly the user.");
const u8 gMoveDescription_ForcePalm[]       = _("Slaps the foe while\nusing a strange\nenergy. May cause\nparalysis.");
const u8 gMoveDescription_Foresight[]       = _("Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_FrenzyPlant[]     = _("The foe is hit with\nan enormous branch.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_Frustration[]     = _("This attack move\ngrows more powerful\nthe less the user\nlikes its TRAINER.");
const u8 gMoveDescription_FuryAttack[]      = _("The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times.");
const u8 gMoveDescription_FuryCutter[]      = _("Slices the foe with\nblades, claws, etc.\nRaises the user's\nATTACK.");
const u8 gMoveDescription_FurySwipes[]      = _("The foe is raked\nwith sharp claws or\nscythes two to five\ntimes.");
const u8 gMoveDescription_FutureSight[]     = _("Two turns after\nthis move is used,\nthe foe is attacked\npsychically.");
const u8 gMoveDescription_GigaDrain[]       = _("A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_Glare[]           = _("The user intimidates\nthe foe with the\ndesign on its belly\nto cause paralysis.");
const u8 gMoveDescription_GrassWhistle[]    = _("A pleasant melody\nis played to lull\nall battlers to\nsleep.");
const u8 gMoveDescription_Growl[]           = _("The user growls in\na cute way, making\nthe foe lower its\nATTACK stat.");
const u8 gMoveDescription_Growth[]          = _("The user's body is\nforced to grow,\nraising the SP.\nATK stat.");
const u8 gMoveDescription_Grudge[]          = _("If the user faints,\nthis move deletes\nthe PP of the move\nthat finished it.");
const u8 gMoveDescription_Guillotine[]      = _("A vicious tearing\nattack with pincers.\nThe foe will faint\nif it hits.");
const u8 gMoveDescription_Gust[]            = _("Strikes the foe\nwith a gust of wind\nwhipped up by\nwings.");
const u8 gMoveDescription_Hail[]            = _("A hailstorm lasting\nfive turns damages\nall POKéMON except\nthe ICE-type.");
const u8 gMoveDescription_Harden[]          = _("The user stiffens\nall the muscles in\nits body to raise\nits DEFENSE stat.");
const u8 gMoveDescription_Haze[]            = _("Eliminates all stat\nchanges among all\nPOKéMON engaged in\nbattle.");
const u8 gMoveDescription_Headbutt[]        = _("The user sticks its\nhead out and rams.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HealBell[]        = _("A soothing bell\nchimes to heal the\nstatus problems of\nall allies.");
const u8 gMoveDescription_HeatWave[]        = _("Blows super-hot\narid winds at foes.\nSuper effective on\nWATER-types.");
const u8 gMoveDescription_HelpingHand[]     = _("A move that boosts\nthe power of the\nally's attack in a\nbattle.");
const u8 gMoveDescription_HiJumpKick[]      = _("A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.");
const u8 gMoveDescription_HiddenPower[]     = _("An attack that\nvaries in type and\nintensity depending\non the user.");
const u8 gMoveDescription_HornAttack[]      = _("The foe is jabbed\nwith a sharply\npointed horn to\ninflict damage.");
const u8 gMoveDescription_HornDrill[]       = _("The horn is rotated\nlike a drill to ram.\nThe foe will faint\nif it hits.");
const u8 gMoveDescription_Howl[]            = _("The user howls to\nraise its spirit and\nboost its ATTACK\nstat.");
const u8 gMoveDescription_HydroCannon[]     = _("The foe is hit with\na watery cannon.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_HydroPump[]       = _("A high volume of\nwater is blasted at\nthe foe under great\npressure.");
const u8 gMoveDescription_HyperBeam[]       = _("A severely damaging\nattack that makes\nthe user rest on\nthe next turn.");
const u8 gMoveDescription_HyperFang[]       = _("The foe is attacked\nwith sharp fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HyperVoice[]      = _("The user lets loose\na horribly loud\nshout with the\npower to damage.");
const u8 gMoveDescription_Hypnosis[]        = _("Hypnotic suggestion\nis used to make the\nfoe fall into a\ndeep sleep.");
const u8 gMoveDescription_IceBall[]         = _("A 3-turn rolling\nattack that becomes\nstronger each time\nit rolls.");
const u8 gMoveDescription_IceBeam[]         = _("The foe is struck\nwith an icy beam.\nIt may leave the\nfoe with frostbite.");
const u8 gMoveDescription_IceFang[]         = _("Bites the foe with\nice infused fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_IcePunch[]        = _("The foe is punched\nwith an icy fist.\nIt may leave the\nfoe with frostbite.");
const u8 gMoveDescription_IcicleSpear[]     = _("Sharp icicles are\nfired at the foe.\nIt strikes two to\nfive times.");
const u8 gMoveDescription_IcyWind[]         = _("A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.");
const u8 gMoveDescription_Imprison[]        = _("Prevents foes from\nusing any move\nthat is also known\nby the user.");
const u8 gMoveDescription_Infestation[]     = _("The foe is infested\nand cannot escape\nfor two to five\nturns.");
const u8 gMoveDescription_Ingrain[]         = _("The user lays roots\nthat restore HP for\nfive turns.\nIt can't switch out.");
const u8 gMoveDescription_IronDefense[]     = _("The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.");
const u8 gMoveDescription_IronTail[]        = _("Wielding a tail\ndenser than metal,\nthe user slams into\nthe foe.");
const u8 gMoveDescription_JumpKick[]        = _("The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.");
const u8 gMoveDescription_KarateChop[]      = _("The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Kinesis[]         = _("The user distracts\nthe foe by bending\na spoon. It may\nlower accuracy.");
const u8 gMoveDescription_KnockOff[]        = _("Knocks down the\nfoe's held item to\nprevent its use\nduring the battle.");
const u8 gMoveDescription_LavaPlume[]       = _("Looses fire on all\nbattlers like a\nvolcano exploding.\nMay cause burns.");
const u8 gMoveDescription_LeafBlade[]       = _("The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_LeechLife[]       = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LeechSeed[]       = _("A seed is planted\non the foe to steal\nsome HP for the \nuser on every turn.");
const u8 gMoveDescription_Leer[]            = _("The foe is given an\nintimidating look\nthat lowers its\nDEFENSE stat.");
const u8 gMoveDescription_Lick[]            = _("The foe is licked\nand hit with a long\ntongue. It may\nalso paralyze.");
const u8 gMoveDescription_LightScreen[]     = _("A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.");
const u8 gMoveDescription_LockOn[]          = _("The user locks on\nto the foe, making\nthe next move sure\nto hit.");
const u8 gMoveDescription_LullabyKiss[]     = _("Impishly tricks the\nfoe into going to\nsleep with a lovely\ngoodnight kiss.");
const u8 gMoveDescription_LowKick[]         = _("A low, tripping kick\nthat inflicts more\ndamage on heavier\nfoes.");
const u8 gMoveDescription_LusterPurge[]     = _("A burst of light\ninjures the foe. It\nmay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MachPunch[]       = _("A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.");
const u8 gMoveDescription_MagicCoat[]       = _("Reflects back the\nfoe's LEECH SEED\nand any status-\ndamaging move.");
const u8 gMoveDescription_MagicalLeaf[]     = _("The foe is attacked\nwith a strange leaf\nthat cannot be\nevaded.");
const u8 gMoveDescription_Magnitude[]       = _("A ground-shaking\nattack against all\nstanding POKéMON.\nIts power varies.");
const u8 gMoveDescription_MeanLook[]        = _("The foe is fixed\nwith a mean look\nthat prevents it\nfrom escaping.");
const u8 gMoveDescription_Meditate[]        = _("The user meditates\nto awaken its power\nand raise its\nATTACK stat.");
const u8 gMoveDescription_MegaDrain[]       = _("A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_MegaKick[]        = _("The foe is attacked\nby a kick fired\nwith muscle-packed\npower.");
const u8 gMoveDescription_MegaPunch[]       = _("The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.");
const u8 gMoveDescription_Megahorn[]        = _("A brutal ramming\nattack delivered\nwith a long horn.\nHurts the user.");
const u8 gMoveDescription_Memento[]         = _("The user faints,\nbut sharply lowers\nthe foe's ATTACK\nand SP. ATK.");
const u8 gMoveDescription_MetalClaw[]       = _("The foe is attacked\nwith steel claws.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_MetalSound[]      = _("A horrible metallic\nscreech is used to\nsharply lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MeteorMash[]      = _("The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_Metronome[]       = _("Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.");
const u8 gMoveDescription_MilkDrink[]       = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_Mimic[]           = _("The user copies the\nmove last used by\nthe foe for the\nrest of the battle.");
const u8 gMoveDescription_MindReader[]      = _("The user predicts\nthe foe's action to\nensure its next\nattack hits.");
const u8 gMoveDescription_Minimize[]        = _("The user compresses\nall the cells in its\nbody to raise its\nevasiveness.");
const u8 gMoveDescription_MirrorCoat[]      = _("A retaliation move\nthat pays back the\nfoe's special attack\ndouble.");
const u8 gMoveDescription_MirrorMove[]      = _("The user counters\nthe move last used\nby the foe with the\nsame move.");
const u8 gMoveDescription_MistBall[]        = _("A flurry of down\nhits the foe. It\nmay also lower the\nfoe's SP. ATK.");
const u8 gMoveDescription_Mist[]            = _("The ally party is\nprotected by a\nmist that prevents\nstat reductions.");
const u8 gMoveDescription_Moonblast[]       = _("An attack using\nchanneled moon\npower. May lower\nthe foe's SP. ATK.");
const u8 gMoveDescription_Moonlight[]       = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_MorningSun[]      = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_MudBomb[]         = _("The user launches\na large glob of\nmud that may lower\nthe foe's accuracy.");
const u8 gMoveDescription_MudShot[]         = _("The user attacks by\nhurling mud.\nMay also reduce the\nfoe's SPEED.");
const u8 gMoveDescription_MudSlap[]         = _("Mud is hurled in\nthe foe's face to\ninflict damage and\nlower its accuracy.");
const u8 gMoveDescription_MudSport[]        = _("Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.");
const u8 gMoveDescription_MuddyWater[]      = _("A wave of muddy\nwater washes over\nfoes. This move is\nalso GROUND-type.");
const u8 gMoveDescription_NaturePower[]     = _("An attack that\nchanges type\ndepending on the\nuser's location.");
const u8 gMoveDescription_NeedleArm[]       = _("An attack using\nthorny arms.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_NightShade[]      = _("An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.");
const u8 gMoveDescription_Nightmare[]       = _("A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.");
const u8 gMoveDescription_Octazooka[]       = _("Ink is blasted in\nthe foe's face or\neyes to damage and\nlower accuracy.");
const u8 gMoveDescription_OdorSleuth[]      = _("Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_Outrage[]         = _("The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_Overheat[]        = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_PainSplit[]       = _("The user adds its\nHP to the foe's HP,\nthen equally shares\nthe total HP.");
const u8 gMoveDescription_PayDay[]          = _("Numerous coins are\nhurled at the foe.\nMoney is earned\nafter battle.");
const u8 gMoveDescription_Peck[]            = _("The foe is jabbed\nwith a sharply\npointed beak or\nhorn.");
const u8 gMoveDescription_PerishSong[]      = _("Any battler that\nhears this faints\nin three turns\nunless it switches.");
const u8 gMoveDescription_PetalDance[]      = _("The user attacks\nwith petals for two\nto three turns,\nthen gets confused.");
const u8 gMoveDescription_PinMissile[]      = _("Sharp pins are shot\nat the foe and hit\ntwo to five times\nat once.");
const u8 gMoveDescription_PoisonFang[]      = _("The foe is bitten\nwith toxic fangs.\nIt may also badly\npoison the foe.");
const u8 gMoveDescription_PoisonGas[]       = _("The battlefield is\ncovered in a cloud\nof poisonous gas.");
const u8 gMoveDescription_PoisonPowder[]    = _("A cloud of toxic\ndust is scattered.\nIt may poison the\nfoe.");
const u8 gMoveDescription_PoisonSting[]     = _("The foe is stabbed\nwith a toxic barb,\netc. It may poison\nthe foe.");
const u8 gMoveDescription_PoisonTail[]      = _("Slams the foe with\na whip-like tail\ncharged with toxic\power.");
const u8 gMoveDescription_Pound[]           = _("A physical attack\ndelivered with a\nlong tail or a\nforeleg, etc.");
const u8 gMoveDescription_PowderSnow[]      = _("Blasts the foe with\na snowy gust.\nIt may leave the\nfoe with frostbite.");
const u8 gMoveDescription_Present[]         = _("Tosses a trapped\npresent to attack.\nTargeted allies are\nhealed instead.");
const u8 gMoveDescription_Protect[]         = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_Psybeam[]         = _("A peculiar ray is\nshot at the foe.\nIt may lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_PsychUp[]         = _("The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.");
const u8 gMoveDescription_Psychic[]         = _("A strong telekinetic\nattack. It may also\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_PsychoBoost[]     = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_Psywave[]         = _("The foe is attacked\nwith an odd, hot\nenergy wave that\nvaries in intensity.");
const u8 gMoveDescription_Pursuit[]         = _("An attack move that\nworks especially\nwell on a foe that\nis switching out.");
const u8 gMoveDescription_QuickAttack[]     = _("An almost invisibly\nfast attack that\nis certain to strike\nfirst.");
const u8 gMoveDescription_Rage[]            = _("An attack that\nbecomes stronger\neach time the user\nis hit in battle.");
const u8 gMoveDescription_RagePowder[]      = _("The user scatters\nirritating powder,\nmaking foes attack\nonly the user.");
const u8 gMoveDescription_RainDance[]       = _("A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.");
const u8 gMoveDescription_RapidSpin[]       = _("An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.");
const u8 gMoveDescription_RazorLeaf[]       = _("The foe is hit with\na cutting leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_RazorWind[]       = _("Blades of wind hit\nthe foe on the 2nd\nturn. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Recover[]         = _("A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.");
const u8 gMoveDescription_Recycle[]         = _("A move that\nrecycles a used\nitem for use once\nmore.");
const u8 gMoveDescription_Reflect[]         = _("A wall of light\ncuts damage from\nphysical attacks\nfor five turns.");
const u8 gMoveDescription_Refresh[]         = _("A self-healing move\nthat cures the user\nof all major status\nailments.");
const u8 gMoveDescription_Rest[]            = _("The user sleeps for\ntwo turns to fully\nrestore HP and heal\nany status problem.");
const u8 gMoveDescription_Return[]          = _("This attack move\ngrows more powerful\nthe more the user\nlikes its TRAINER.");
const u8 gMoveDescription_Revenge[]         = _("An attack move that\ngains in intensity if\nthe target has hurt\nthe user.");
const u8 gMoveDescription_Reversal[]        = _("An all-out attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Roar[]            = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_RockBlast[]       = _("The user hurls two\nto five hard rocks\nat the foe to\nattack.");
const u8 gMoveDescription_RockSlide[]       = _("Large boulders are\nhurled at the foe.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_RockSmash[]       = _("An attack that may\nalso cut DEFENSE.\nIt can also smash\ncracked boulders.");
const u8 gMoveDescription_RockThrow[]       = _("The foe is attacked\nwith a shower of\nsmall, easily\nthrown rocks.");
const u8 gMoveDescription_RockTomb[]        = _("Boulders are hurled\nat the foe. It also\nlowers the foe's\nSPEED if it hits.");
const u8 gMoveDescription_RolePlay[]        = _("The user mimics the\nfoe completely and\ncopies the foe's\nability.");
const u8 gMoveDescription_RollingKick[]     = _("A quick kick from a\nrolling spin.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Rollout[]         = _("A 3-turn rolling\nattack that becomes\nstronger each time\nit hits.");
const u8 gMoveDescription_SacredFire[]      = _("Cleansing flames\nassault the foe but\ncan heal targeted\nallies instead.");
const u8 gMoveDescription_Safeguard[]       = _("It protects the\nuser's party from\nall status problems\nfor five turns.");
const u8 gMoveDescription_SandAttack[]      = _("Blows sand at the\nfoes. Always goes\nfirst and lowers\ntheir accuracy.");
const u8 gMoveDescription_SandTomb[]        = _("The foe is trapped\ninside a painful\nsandstorm for two\nto five turns.");
const u8 gMoveDescription_Sandstorm[]       = _("A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.");
const u8 gMoveDescription_ScaryFace[]       = _("Frightens the foe\nwith a scary face\nto sharply reduce\nits SPEED.");
const u8 gMoveDescription_Scratch[]         = _("Hard, pointed, and\nsharp claws rake\nthe foe.");
const u8 gMoveDescription_Screech[]         = _("An ear-splitting\nscreech is emitted\nto sharply reduce\nthe foe's DEFENSE.");
const u8 gMoveDescription_SecretPower[]     = _("An attack that may\nhave an additional\neffect that varies\nwith the terrain.");
const u8 gMoveDescription_SeismicToss[]     = _("A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.");
const u8 gMoveDescription_SelfDestruct[]    = _("The user blows up\nto inflict severe\ndamage, even\nmaking itself faint.");
const u8 gMoveDescription_ShadowBall[]      = _("A shadowy blob is\nhurled at the foe.\nMay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_ShadowPunch[]     = _("The user throws a\npunch from the\nshadows. It cannot\nbe evaded.");
const u8 gMoveDescription_Sharpen[]         = _("The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.");
const u8 gMoveDescription_SheerCold[]       = _("Covers the foe with\nconcentrated ice\nenergy, giving the\nfoe frostbite.");
const u8 gMoveDescription_ShockWave[]       = _("A rapid jolt of\nelectricity strikes\nthe foe. It can't\nbe evaded.");
const u8 gMoveDescription_SignalBeam[]      = _("The foe is hit with\na flashing beam\nthat may also\ncause confusion.");
const u8 gMoveDescription_SilverWind[]      = _("The foe is attacked\nwith a silver dust.\nIt may poison the\nfoe.");
const u8 gMoveDescription_Sing[]            = _("A soothing song\nin a calming voice\nlulls the foe into\na deep slumber.");
const u8 gMoveDescription_Sketch[]          = _("This move copies\nthe move last used\nby the foe, then\ndisappears.");
const u8 gMoveDescription_SkillSwap[]       = _("The user employs\nits psychic power\nto swap abilities\nwith the foe.");
const u8 gMoveDescription_SkullBash[]       = _("The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_SkyAttack[]       = _("Dives from the sky\nto attack the foe.\nIf it misses, the\nuser is hurt.");
const u8 gMoveDescription_SkyUppercut[]     = _("An uppercut thrown\nskyward with force.\nSuper effective on\nFLYING-types.");
const u8 gMoveDescription_SlackOff[]        = _("The user slacks off\nand restores its HP\nby half its full\nHP.");
const u8 gMoveDescription_Slam[]            = _("The foe is struck\nwith a long tail,\nvines, etc.");
const u8 gMoveDescription_Slash[]           = _("The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SleepPowder[]     = _("A sleep-inducing\ndust is scattered\nin high volume\naround a foe.");
const u8 gMoveDescription_SleepTalk[]       = _("While asleep, the\nuser randomly uses\none of the moves it\nknows.");
const u8 gMoveDescription_SludgeBomb[]      = _("Filthy sludge is\nhurled at the foe.\nIt may poison the\ntarget.");
const u8 gMoveDescription_Sludge[]          = _("The foe is covered\nin a thick, viscous\nsludge. May lower\nthe foe's SPEED.");
const u8 gMoveDescription_SmellingSalt[]    = _("Doubly effective on\na paralyzed foe,\nbut it also cures\nthe foe's paralysis.");
const u8 gMoveDescription_Smog[]            = _("The foe is attacked\nwith exhaust gases.\nIt may also poison\nthe foe.");
const u8 gMoveDescription_Smokescreen[]     = _("An obscuring cloud\nof smoke or ink\nreduces the foe's\naccuracy.");
const u8 gMoveDescription_Snarl[]           = _("The user yells as\nif ranting about\nsomething. Lowers\nall foes' SP. ATK.");
const u8 gMoveDescription_Snatch[]          = _("Steals the effects\nof the foe's\nhealing or status-\nchanging move.");
const u8 gMoveDescription_Snore[]           = _("An attack that can\nbe used only while\nasleep. It may\ncause flinching.");
const u8 gMoveDescription_SoftBoiled[]      = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_SolarBeam[]       = _("A 2-turn move that\nblasts the foe with\nabsorbed energy in\nthe 2nd turn.");
const u8 gMoveDescription_SonicBoom[]       = _("The user creates a\nbig shockwave that\ndeals their level\nin damage.");
const u8 gMoveDescription_Spark[]           = _("An electrically\ncharged tackle that\nmay also paralyze\nthe foe.");
const u8 gMoveDescription_SpiderWeb[]       = _("Ensnares the foe \nwith sticky string\nso it doesn't flee\nor switch out.");
const u8 gMoveDescription_SpikeCannon[]     = _("Sharp spikes are\nfired at the foe to\nstrike two to five\ntimes.");
const u8 gMoveDescription_Spikes[]          = _("A trap of spikes is\nlaid around the\nfoe's party to hurt\nfoes switching in.");
const u8 gMoveDescription_SpitUp[]          = _("The power built\nusing STOCKPILE is\nreleased at once\nfor attack.");
const u8 gMoveDescription_Spite[]           = _("A move that cuts\n2 to 5 PP from the\nmove last used by\nthe foe.");
const u8 gMoveDescription_Splash[]          = _("The user just flops\nand splashes around\nwithout having any\neffect.");
const u8 gMoveDescription_Spore[]           = _("The user scatters\nbursts of fine\nspores that induce\nsleep.");
const u8 gMoveDescription_SteelWing[]       = _("The foe is hit with\nwings of steel.\nIt may also raise\nthe user's DEFENSE.");
const u8 gMoveDescription_Stockpile[]       = _("The user charges\nup power for use\nlater. It can be\nused three times.");
const u8 gMoveDescription_Stomp[]           = _("The foe is stomped\ninto the ground.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Strength[]        = _("The foe is slugged\nat maximum power.\nMay also raise the\nuser's ATTACK.");
const u8 gMoveDescription_StringShot[]      = _("Spits sticky string\nat foes, binding\nthem and reducing\nSPEED and EVASION.");
const u8 gMoveDescription_Struggle[]        = _("An attack that is\nused only if there\nis no PP. It also\nhurts the user.");
const u8 gMoveDescription_StruggleBug[]     = _("The user struggles\nwith all its might.\nLowers the SP. ATK\nof all foes.");
const u8 gMoveDescription_StunSpore[]       = _("Paralyzing dust is\nscattered wildly.\nIt may paralyze\nthe foe.");
const u8 gMoveDescription_Submission[]      = _("A reckless, full-\nbody throw attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_Substitute[]      = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_SunnyDay[]        = _("The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.");
const u8 gMoveDescription_SuperFang[]       = _("The user attacks\nwith sharp fangs\nand halves the\nfoe's HP.");
const u8 gMoveDescription_Superpower[]      = _("A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.");
const u8 gMoveDescription_Supersonic[]      = _("The user generates\nodd sound waves.\nIt may confuse the\nfoe.");
const u8 gMoveDescription_Surf[]            = _("A big wave crashes\ndown on the foe.\nCan also be used\nfor crossing water.");
const u8 gMoveDescription_Swagger[]         = _("A move that makes\nthe foe confused,\nbut also sharply\nraises its ATTACK.");
const u8 gMoveDescription_Swallow[]         = _("The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.");
const u8 gMoveDescription_SweetKiss[]       = _("The user kisses\nthe foe with sweet\ncuteness that\ncauses confusion.");
const u8 gMoveDescription_SweetScent[]      = _("Allures the foe to\nreduce evasiveness.\nIt also attracts\nwild POKéMON.");
const u8 gMoveDescription_Swift[]           = _("Star-shaped rays\nthat never miss are\nfired at all foes in\nbattle.");
const u8 gMoveDescription_SwordsDance[]     = _("A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.");
const u8 gMoveDescription_Synthesis[]       = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Tackle[]          = _("A physical attack\nin which the user\ncharges, full body,\ninto the foe.");
const u8 gMoveDescription_TailGlow[]        = _("The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.");
const u8 gMoveDescription_TailWhip[]        = _("The user wags its\ntail cutely, making\nthe foe lower its\nDEFENSE stat.");
const u8 gMoveDescription_TakeDown[]        = _("A reckless, full-\nbody charge attack\nthat also hurts the\nuser a little.");
const u8 gMoveDescription_Taunt[]           = _("The foe is taunted\ninto a rage that\nallows it to use\nonly attack moves.");
const u8 gMoveDescription_TeeterDance[]     = _("A wobbly dance\nthat confuses all\nthe POKéMON in\nbattle.");
const u8 gMoveDescription_Teleport[]        = _("Use it to flee from\nany wild POKéMON.\nAlso warps to the\nlast POKé CENTER.");
const u8 gMoveDescription_Thief[]           = _("An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.");
const u8 gMoveDescription_Thrash[]          = _("The user rampages\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_ThunderFang[]     = _("Bites the foe with\nelectricity infused\nfangs. It may make\nthe foe flinch.");
const u8 gMoveDescription_ThunderPunch[]    = _("The foe is punched\nwith an electrified\nfist. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_ThunderShock[]    = _("An electric shock\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_ThunderWave[]     = _("A weak electric\nshock that is sure\nto cause paralysis\nif it hits.");
const u8 gMoveDescription_Thunder[]         = _("A brutal lightning\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_Thunderbolt[]     = _("A strong electrical\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_Tickle[]          = _("The foe is made to\nlaugh, reducing its\nATTACK and DEFENSE\nstats.");
const u8 gMoveDescription_Torment[]         = _("It enrages the foe,\nmaking it incapable\nof using the same\nmove successively.");
const u8 gMoveDescription_Toxic[]           = _("A move that badly\npoisons the foe.\nIts poison damage\nworsens every turn.");
const u8 gMoveDescription_Transform[]       = _("The user transforms\ninto a copy of the\nfoe with even the\nsame move set.");
const u8 gMoveDescription_TriAttack[]       = _("A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the foe.");
const u8 gMoveDescription_Trick[]           = _("A move that tricks\nthe foe into\ntrading held items\nwith the user.");
const u8 gMoveDescription_TripleKick[]      = _("A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.");
const u8 gMoveDescription_Twineedle[]       = _("The foe is stabbed\ntwice with foreleg\nstingers. It may\npoison the foe.");
const u8 gMoveDescription_Twister[]         = _("Whips up a vicious\ntwister to attack\nfoes. This move is\nalso FLYING-type.");
const u8 gMoveDescription_Uproar[]          = _("The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.");
const u8 gMoveDescription_UTurn[]           = _("The user attacks\nand reverses course\nto switch out with\na party member.");
const u8 gMoveDescription_VenomJab[]        = _("Jabs the foe with a\nvenom-soaked limb.\nIt may lower the\nfoe's DEFENSE.");
const u8 gMoveDescription_ViceGrip[]        = _("Huge, impressive\npincers grip and\nsqueeze the foe.");
const u8 gMoveDescription_VineWhip[]        = _("The foe is struck\nwith slender, whip-\nlike vines.");
const u8 gMoveDescription_VitalThrow[]      = _("Makes the user\nattack after the\nfoe. In return,\nit will not miss.");
const u8 gMoveDescription_VoltSwitch[]      = _("The user attacks\nand reverses course\nto switch out with\na party member.");
const u8 gMoveDescription_VoltTackle[]      = _("The user throws an\nelectrified tackle.\nIt hurts the user\na little.");
const u8 gMoveDescription_WaterGun[]        = _("The foe is struck\nwith a lot of water\nexpelled forcibly\nfrom the mouth.");
const u8 gMoveDescription_WaterPulse[]      = _("An attack with a\npulsing blast of\nwater. It may also\nconfuse the foe.");
const u8 gMoveDescription_WaterSport[]      = _("Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.");
const u8 gMoveDescription_WaterSpout[]      = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_Waterfall[]       = _("A powerful charge\nattack. It can also\nbe used to climb\na waterfall.");
const u8 gMoveDescription_WeatherBall[]     = _("An attack that\nvaries in power and\ntype depending on\nthe weather.");
const u8 gMoveDescription_Whirlpool[]       = _("The foe is trapped\nin a fast, vicious\nwhirlpool for two\nto five turns.");
const u8 gMoveDescription_Whirlwind[]       = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_WildCharge[]      = _("Slams into the foe\nwhile charged with\nenergy. May raise\nthe user's SPEED.");
const u8 gMoveDescription_WillOWisp[]       = _("A sinister, bluish\nwhite flame is shot\nat the foe to\ninflict a burn.");
const u8 gMoveDescription_WingAttack[]      = _("The foe is struck\nwith large, imposing\nwings spread wide.");
const u8 gMoveDescription_Wish[]            = _("A self-healing move\nthat restores half\nthe full HP on the\nnext turn.");
const u8 gMoveDescription_Withdraw[]        = _("The user withdraws\nits body in its hard\nshell, raising both\nof its defenses.");
const u8 gMoveDescription_Wrap[]            = _("A long body or\nvines are used to\nwrap the foe for\ntwo to five turns.");
const u8 gMoveDescription_XScissor[]        = _("The user slices the\nfoe with crossed\nclaws. Has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Yawn[]            = _("A huge yawn lulls\nthe foe into falling\nasleep on the next\nturn.");
const u8 gMoveDescription_ZapCannon[]       = _("An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_AURA_SPHERE   - 1] = gMoveDescription_AuraSphere,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_BUG_BUZZ      - 1] = gMoveDescription_BugBuzz,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_CHARGE_BEAM   - 1] = gMoveDescription_ChargeBeam,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_DARK_PULSE    - 1] = gMoveDescription_DarkPulse,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_DISARMING_CRY - 1] = gMoveDescription_DisarmingCry,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_DRAGON_TAIL   - 1] = gMoveDescription_DragonTail,
    [MOVE_DRAIN_KISS    - 1] = gMoveDescription_DrainKiss,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_DRILL_RUN     - 1] = gMoveDescription_DrillRun,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_EARTH_AURA    - 1] = gMoveDescription_EarthAura,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_FEINT_ATTACK  - 1] = gMoveDescription_FeintAttack,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_FIRE_FANG     - 1] = gMoveDescription_FireFang,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_FLAME_CHARGE  - 1] = gMoveDescription_FlameCharge,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_FOCUS_BLAST   - 1] = gMoveDescription_FocusBlast,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_FORCE_PALM    - 1] = gMoveDescription_ForcePalm,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_ICE_FANG      - 1] = gMoveDescription_IceFang,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_INFESTATION   - 1] = gMoveDescription_Infestation,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_LAVA_PLUME    - 1] = gMoveDescription_LavaPlume,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_LULLABY_KISS  - 1] = gMoveDescription_LullabyKiss,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_MOONBLAST     - 1] = gMoveDescription_Moonblast,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_MUD_BOMB      - 1] = gMoveDescription_MudBomb,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_RAGE_POWDER   - 1] = gMoveDescription_RagePowder,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_SNARL         - 1] = gMoveDescription_Snarl,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_STRUGGLE_BUG  - 1] = gMoveDescription_StruggleBug,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_FANG  - 1] = gMoveDescription_ThunderFang,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_U_TURN        - 1] = gMoveDescription_UTurn,
    [MOVE_VENOM_JAB     - 1] = gMoveDescription_VenomJab,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_VOLT_SWITCH   - 1] = gMoveDescription_VoltSwitch,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_WILD_CHARGE   - 1] = gMoveDescription_WildCharge,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_X_SCISSOR     - 1] = gMoveDescription_XScissor,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
};
